---
swagger: "2.0"
info:
  title: "home-console"
host: ${API_GATEWAY_HOST}
basePath: "/default"
schemes:
- "https"
paths:
  /auth:
    post:
      produces:
      - "application/json"
      parameters:
      - name: "Content-Type"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Content-Type:
              type: "string"
  /{proxy+}:
    x-amazon-apigateway-any-method:
      parameters:
      - name: "Content-Type"
        in: "header"
        required: true
        type: "string"
      - name: "Accept"
        in: "header"
        required: false
        type: "string"
      - name: "proxy"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Content-Length:
              type: "string"
            Content-Type:
              type: "string"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
